baseURL = "https://www.nuba-tek.com/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Nuba Tek"
themesDir = "themes"
theme = "nubatek-theme"


[languages]
  [languages.fr]
     lang = "fr"
     languageName = "Français"
     weight = 0

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
    google_analytics_id=""

[params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Nuba Tek"

[params.homepage_meta_tags]
    meta_description    = "Site web de la société Nuba Tek"
    meta_og_title       = "Nuba Tek"
    meta_og_type        = "website"
    meta_og_url         = "https://www.nuba-tek.com"
    meta_og_image       = ""
    meta_og_description = "Site web de la société Nuba Tek"
    meta_twitter_card   = "summary"
    meta_twitter_site   = ""
    meta_twitter_creator = ""

[[menu.main]]
   name = "Accueil"
   url = "/"
   weight = 1

[[menu.main]]
   name = "Postulez"
   url = "/postes/"
   weight = 2

[[menu.main]]
   name = "Contact"
   url = "/contact/"
   weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
